Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.8.1/libexec/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/main.py", line 704, in main
    config = configuration.NamespaceConfig(args)
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/configuration.py", line 45, in __init__
    check_config_sanity(self)
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/configuration.py", line 129, in check_config_sanity
    "on the same port ({0})".format(config.tls_sni_01_port))
ConfigurationError: Trying to run http-01 and tls-sni-01 on the same port (4443)
